try github cache of kernel rpms

diff --git a/.github/workflows/reusable-build.yml b/.github/workflows/reusable-build.yml
--- a/.github/workflows/reusable-build.yml
+++ b/.github/workflows/reusable-build.yml
@@ -37,26 +37,28 @@ jobs:
             kernel_flavor: asus
           - fedora_version: 40
             kernel_flavor: bazzite
+    outputs:
+      CKKEY: ${{ steps.kernel-version.outputs.CKKEY }}
+      CKPATH: /tmp/cache-kernel/rpms
+      kernel_build_tag: ${{ steps.kernel-version.outputs.kernel_build_tag }}
+      KERNEL_VERSION: ${{ steps.kernel-version.outputs.kernel_release }}
     env:
       CKWD: /tmp/cache-kernel
+      CKPATH: /tmp/cache-kernel/rpms
 
     steps:
       - name: Checkout Push to Registry action
         uses: actions/checkout@v4
 
-      - name: Install Tools
+      - name: Install Basic Tools
         run: |
           dnf -y install --setopt=install_weak_deps=False \
-            curl \
             dnf-plugins-core \
             jq \
-            openssl \
-            rpmrebuild \
-            sbsigntools \
             skopeo
 
       - name: Get Kernel Version
-        id: Version
+        id: kernel-version
         shell: bash
         run: |
           coreos_kernel () {
@@ -159,13 +161,28 @@ jobs:
             minor=$(echo "$linux" | cut -d '.' -f 2)
             patch=$(echo "$linux" | cut -d '.' -f 3)
             kernel_major_minor_patch="${major}.${minor}.${patch}"
-            echo "Kernel Version is ${linux}"
+
+            echo "kernel_flavor: ${{ matrix.kernel_flavor }}"
+            echo "kernel_release: ${linux}"
+            echo "kernel_build_tag: ${build_tag}"
+
             echo "kernel_release=${linux}" >> $GITHUB_ENV
             echo "kernel_build_tag=${build_tag}" >> $GITHUB_ENV
             echo "kernel_major_minor_patch=${kernel_major_minor_patch}" >> $GITHUB_ENV
 
+            echo "kernel_release=${linux}" >> $GITHUB_OUTPUT
+            echo "kernel_build_tag=${build_tag}" >> $GITHUB_OUTPUT
+            echo "CKKEY=${{ matrix.kernel_flavor }}-${linux}" >> $GIBHUB_OUTPUT
+
+      - name: Cache Kernel RPMs
+        id: cache-kernel
+        uses: actions/cache@v4
+        with:
+          path: ${{ env.CKPATH }}
+          key: ${{ needs.cache-kernel.outputs.CKKEY }}
+
       - name: Retrieve Signing Key
-        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'merge_group'
+        if: steps.cache-kernel.outputs.cache-hit != 'true' && github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'merge_group'
         shell: bash
         run: |
           mkdir -p certs
@@ -180,7 +197,16 @@ jobs:
             wc -c certs/private_key_2.priv
           fi
 
+      - name: Install Tools for Rebuild/Signing
+        if: steps.cache-kernel.outputs.cache-hit != 'true'
+        run: |
+          dnf -y install --setopt=install_weak_deps=False \
+            openssl \
+            rpmrebuild \
+            sbsigntools
+
       - name: Fetch and Sign Kernel Packages
+        if: steps.cache-kernel.outputs.cache-hit != 'true'
         shell: bash
         run: |
           export FEDORA_VERSION=${{ matrix.fedora_version }}
@@ -197,8 +223,8 @@ jobs:
 
           find ${{ env.CKWD }}
 
-
       - name: Check Secureboot Signatures
+        if: steps.cache-kernel.outputs.cache-hit != 'true'
         shell: bash
         run: |
           set -x
@@ -224,7 +250,16 @@ jobs:
           sbverify --cert akmods.crt vmlinuz || exit 1
           cd $HOME
 
-          find ${{ env.CKWD }}/rpms
+      - name: Add Date to Kernel Cache
+        if: steps.cache-kernel.outputs.cache-hit != 'true'
+        shell: bash
+        run: |
+          echo "$(date '+%Y%m%d.0')" > ${{ env.CKPATH }}/kernel-cache-date
+
+      - name: List Cached Kernel RPMs
+        shell: bash
+        run: |
+          find ${{ env.CKPATH }}
 
   build-akmods:
     name: Build kmods ${{ inputs.fedora_version }}-${{ inputs.kernel_flavor }}
@@ -260,11 +295,28 @@ jobs:
             cfile_suffix: zfs
           - kernel_flavor: surface
             cfile_suffix: zfs
+    env:
+      CKPATH: ${{ needs.cache-kernel.outputs.CKPATH }}
+      kernel_build_tag: ${{ needs.cache-kernel.outputs.kernel_build_tag }}
+      KERNEL_VERSION: ${{ needs.cache-kernel.outputs.KERNEL_VERSION }}
 
     steps:
       # Checkout push-to-registry action GitHub repository
       - name: Checkout Push to Registry action
         uses: actions/checkout@v4
+
+      - name: Cache Kernel RPMs
+        id: cache-kernel
+        uses: actions/cache@v4
+        with:
+          path: ${{ env.CKPATH }}
+          key: ${{ needs.cache-kernel.outputs.CKKEY }}
+
+      - name: Fail Absent Kernel Cache
+        if: steps.cache-kernel.outputs.cache-hit = 'false'
+        run: |
+          echo "Kernel Cache not found for key: ${{ needs.cache-kernel.outputs.CKKEY }}"
+          exit 1
 
       - name: Matrix Variables
         shell: bash
@@ -277,9 +329,21 @@ jobs:
           export BUILDER_IMAGE=quay.io/fedora/fedora
           echo "BUILDER_IMAGE=${BUILDER_IMAGE}" >> $GITHUB_ENV
           echo "FQ_BUILDER_IMAGE=${BUILDER_IMAGE}:${{ matrix.fedora_version }}" >> $GITHUB_ENV
-          export KERNEL_IMAGE=${{ matrix.kernel_flavor }}-kernel
-          echo "KERNEL_IMAGE=${KERNEL_IMAGE}" >> $GITHUB_ENV
-          echo "FQ_KERNEL_IMAGE=${{ env.IMAGE_REGISTRY }}/${KERNEL_IMAGE}:${{ matrix.fedora_version }}" >> $GITHUB_ENV
+
+      - name: Get Cached Kernel Date/Version
+        shell: bash
+        run: |
+          set -exo pipefail
+
+          KCDATE=$(cat ${{ env.CKPATH }}/kernel-cache-date)
+          if [ -z "${KCDATE}" ]; then
+            echo "kernel-cache-date must not be empty"
+          fi
+          if [ -z "${{ env.KERNEL_VERSION }}" ]; then
+            echo "KERNEL_VERSION must not be empty"
+          fi
+          KERNEL_IMAGE_VERSION=${{ env.KERNEL_VERSION }}-${date}
+          echo "KERNEL_IMAGE_VERSION=$img_version" >> $GITHUB_ENV
 
       - name: AppArmor Disable
         run: |
@@ -297,33 +361,6 @@ jobs:
             # pull the base image used for FROM in containerfile so
             # we can retry on that unfortunately common failure case
             podman pull ${{ env.FQ_BUILDER_IMAGE }}
-            podman pull ${{ env.FQ_KERNEL_IMAGE }}
-
-      - name: Get current version
-        shell: bash
-        run: |
-          set -eo pipefail
-
-          #skopeo inspect containers-storage:${{ env.FQ_KERNEL_IMAGE }} > kernel.json
-          # We SHOULD be able to use container-storage to inspect already pulled image here
-          # BUT... ubuntu-24.04 builders prevent with this error:
-          #     Error during unshare(...): Operation not permitted
-          # I intend to investigate/fix later, but need to move forward
-          skopeo inspect docker://${{ env.FQ_KERNEL_IMAGE }} > kernel.json
-
-          linux=$(jq -r '.["Labels"]["ostree.linux"]' kernel.json)
-          if [ -z "$linux" ] || [ "null" = "$linux" ]; then
-            echo "inspected linux version must not be empty or null"
-            exit 1
-          fi
-          echo "KERNEL_VERSION=$linux" >> $GITHUB_ENV
-
-          img_version=$(jq -r '.["Labels"]["org.opencontainers.image.version"]' kernel.json)
-          if [ -z "$img_version" ] || [ "null" = "$img_version" ]; then
-            echo "inspected image version must not be empty or null"
-            exit 1
-          fi
-          echo "KERNEL_IMAGE_VERSION=$img_version" >> $GITHUB_ENV
 
       - name: Generate tags
         id: generate-tags
@@ -393,6 +430,10 @@ jobs:
             wc -c certs/private_key.priv
             wc -c certs/private_key_2.priv
           fi
+
+      - name: TEMP SHORT CIRCUIT
+        run: |
+          exit 1
 
       # Build image using Buildah action
       - name: Build Image
